packages:
  - 'packages/*'
  - 'playground/**'
  - 'packages/plugin-react-swc/playground/**'
  - 'packages/plugin-rsc/examples/*'

catalogs:
  rolldown-vite:
    vite: npm:rolldown-vite@^7.0.9

overrides:
  '@types/estree': ^1.0.8
  'vitest>vite': npm:vite@^6.2.6
  'vite': https://pkg.pr.new/vitejs/rolldown-vite@bdb70a9
