packages:
  - 'packages/*'
  - 'playground/**'
  - 'packages/plugin-react-swc/playground/**'
  - 'packages/plugin-rsc/examples/*'

catalogs:
  rolldown-vite:
    vite: npm:rolldown-vite@^7.1.2

overrides:
  '@types/estree': ^1.0.8

dedupeInjectedDeps: false

peerDependencyRules:
  ignoreMissing:
    # ignore react-server-dom-webpack -> webpack
    - webpack
