packages:
  - 'packages/*'
  - 'playground/**'
  - 'packages/plugin-react-swc/playground/**'
  - 'packages/plugin-rsc/examples/*'

catalogs:
  rolldown-vite:
    vite: npm:rolldown-vite@^7.0.10

overrides:
  '@types/estree': ^1.0.8
  vite: "npm:rolldown-vite@latest"

dedupeInjectedDeps: false
