packages:
  - 'packages/*'
  - 'playground/**'
  - 'packages/plugin-react-swc/playground/**'
  - 'packages/plugin-rsc/examples/*'

catalogs:
  rolldown-vite:
    vite: npm:rolldown-vite@^7.1.5

overrides:
  '@types/estree': ^1.0.8
  'vitest>vite': npm:vite@^7.1.3
  'vite': npm:rolldown-vite@^7.1.5

dedupeInjectedDeps: false

peerDependencyRules:
  ignoreMissing:
    # ignore react-server-dom-webpack -> webpack
    - webpack
