packages:
  - 'packages/*'
  - 'playground/**'
  - 'packages/plugin-react-swc/playground/**'
  - 'packages/plugin-rsc/examples/*'

catalogs:
  rolldown-vite:
    vite: npm:rolldown-vite@^7.3.1

dedupeInjectedDeps: false

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - playwright-chromium
  - sharp
  - simple-git-hooks
  - unrs-resolver
  - workerd

overrides:
  '@types/estree': ^1.0.8
  vite: 8.0.0-beta.14

peerDependencyRules:
  ignoreMissing:
    # ignore react-server-dom-webpack -> webpack
    - webpack
