packages:
  - 'packages/*'
  - 'playground/**'
  - 'packages/plugin-react-swc/playground/**'
  - 'packages/plugin-rsc/examples/*'

catalogs:
  rolldown-vite:
    # vite: npm:rolldown-vite@^7.1.0
    vite: https://pkg.pr.new/vitejs/rolldown-vite@376

overrides:
  '@types/estree': ^1.0.8
  # vite: npm:rolldown-vite@^7.1.0
  # vite: https://pkg.pr.new/vitejs/rolldown-vite@376

dedupeInjectedDeps: false

peerDependencyRules:
  ignoreMissing:
    # ignore react-server-dom-webpack -> webpack
    - webpack
