import { readFileSync, writeFileSync } from 'node:fs'
import {
  extractChangelogEntry,
  generateChangelog,
  prepareRelease,
} from '@vitejs/release-scripts'

const releasePackages = [
  'plugin-react',
  'plugin-react-swc',
  'plugin-rsc',
] as const

function getRequiredEnv(name: string): string {
  const value = process.env[name]
  if (!value) throw new Error(`${name} is required`)
  return value
}

async function main() {
  const pkg = process.argv[2]
  const githubServerUrl = getRequiredEnv('GITHUB_SERVER_URL')
  const githubRepository = getRequiredEnv('GITHUB_REPOSITORY')
  const githubRunId = getRequiredEnv('GITHUB_RUN_ID')

  const { tag, version } = await prepareRelease({
    packages: releasePackages,
    pkg,
    release: process.argv[3],
    generateChangelog: async (pkg, version) => {
      const pkgDir = `packages/${pkg}`
      if (pkg === 'plugin-rsc') {
        await generateChangelog({
          getPkgDir: () => pkgDir,
          tagPrefix: `${pkg}@`,
        })
        return
      }
      const changelogPath = `${pkgDir}/CHANGELOG.md`
      const changelog = readFileSync(changelogPath, 'utf-8')
      const date = new Date().toISOString().slice(0, 10)
      writeFileSync(
        changelogPath,
        changelog.replace(
          '## Unreleased',
          `## Unreleased\n\n## ${version} (${date})`,
        ),
      )
    },
  })

  const changelog = extractChangelogEntry({
    changelogPath: `packages/${pkg}/CHANGELOG.md`,
    version,
  })
  const prBody = [
    `${pkg} release PR generated by the Prepare Release workflow: ${githubServerUrl}/${githubRepository}/actions/runs/${githubRunId}`,
    '',
    '## Changelog',
    '',
    changelog,
  ].join('\n')
  const delimiter = '__VITE_RELEASE_PR_BODY_EOF__'

  console.log(
    `tag=${tag}\nversion=${version}\npr_body<<${delimiter}\n${prBody}\n${delimiter}`,
  )
}

main().catch((error) => {
  console.error('Error preparing release:', error)
  process.exit(1)
})
