name: Lock Closed Issues

on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read # to check out the repo for local actions
  issues: write

jobs:
  action:
    if: github.repository == 'vitejs/vite-plugin-react'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          persist-credentials: false
          ref: main

      - uses: ./.github/actions/issues-helper
        with:
          actions: lock-closed-issues
          token: ${{ secrets.GITHUB_TOKEN }}
          inactive-day: 14
