name: Preview Publish

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, labeled]

permissions: {}

jobs:
  preview:
    if: >
      github.repository == 'vitejs/vite-plugin-react' &&
      (github.event_name == 'push' ||
      (github.event_name == 'pull_request'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6.0.3

      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          # disable cache, to avoid cache poisoning (https://docs.zizmor.sh/audits/#cache-poisoning)
          package-manager-cache: false

      - name: Disallow installation scripts
        run: yq '.onlyBuiltDependencies = []' -i pnpm-workspace.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Publish
        run: pnpm dlx pkg-pr-new@0.0 publish --pnpm --compact './packages/*' './packages/plugin-react-swc/dist'
